name: Lint
on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.rubocop.yml'
      - 'Gemfile*'
      - 'Rakefile'
      - 'fluent-plugin-kubernetes_metadata_filter.gemspec'
      - '**/*.rb'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rake rubocop
